# Generated by Django 3.2.25 on 2024-09-22 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cartitmes',
            new_name='CartItme',
        ),
    ]
